#Start with a base image containing Java runtime
FROM openjdk:1.8-jdk-slim as build

#Information around who maintains the image
MAINTAINER eazybytes.com

# Add the application's jar to the container
COPY target/ReactDock-0.0.1-SNAPSHOT.jar ReactDock-0.0.1-SNAPSHOT.jar

#execute the application
ENTRYPOINT ["java","-jar","/ReactDock-0.0.1-SNAPSHOT.jar"]